Spawning 1 workers to process statsv messages
Starting statsv Kafka consumer.
MediaWiki.foo:1|c
statsv_messages_handled_total:1|c|#format:statsd
MediaWiki.foo:20|c
MediaWiki.quux:21|ms
statsv_messages_handled_total:2|c|#format:statsd
Discarded dogstatsd message: ""
Discarded dogstatsd message: "MediaWiki.no_equals_value_single"
MediaWiki.foo:50|c
statsv_messages_handled_total:1|c|#format:statsd
MediaWiki.recover_after_invalid:60|c
MediaWiki.quux:61|ms
statsv_messages_handled_total:2|c|#format:statsd
Discarded dogstatsd message: "something_non_mediawiki_total:1|c"
Discarded dogstatsd message: "mediawiki_missing_total_suffix:1|c"
mediawiki_after_bad_name_total:1|c
statsv_messages_handled_total:1|c|#format:dogstatsd
Discarded dogstatsd message: "mediawiki_example_total:|c"
Discarded dogstatsd message: "mediawiki_example_total:1|g"
Discarded dogstatsd message: "mediawiki_example_total:1|ms"
mediawiki_example_total:1|c
mediawiki_example_total:42|c|#key1:value1,key2:value2
statsv_messages_handled_total:2|c|#format:dogstatsd
Discarded dogstatsd message: "mediawiki_foo_rows:200|g"
Discarded dogstatsd message: "mediawiki_foo_seconds:200|ms"
Reached end of fixture file.
Caught exception, aborting.
Traceback (most recent call last):
File "/statsv/statsv.py", line 0, in statsv_main
  raise RuntimeError('No messages received in %d seconds.' % args.consumer_timeout_seconds)
RuntimeError: No messages received in 60 seconds.
